create table mock.data3 (
	address VARCHAR(255),
	status VARCHAR(255),
	grp INT,
	app_date DATE,
	status2 VARCHAR(255),
	done VARCHAR(255),
	type_a VARCHAR(255)
);
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('452 Rieder Junction', 'stable', 1, '10/4/2014', null, true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values (null, 'updated', 2, null, null, null, null);
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('91 Oneill Trail', 'updated', 3, '6/16/2015', null, true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('57052 Myrtle Way', 'depreciated', 2, '10/29/2014', 'inprogress', true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('4541 Schiller Center', 'stable', null, '8/4/2015', 'cancelled', true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('57052 Myrtle Way', 'stable', null, '11/26/2014', 'cancelled', false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('98 Arkansas Place', null, 1, '6/12/2015', 'stalled', true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('0987 Lunder Junction', null, 3, '1/28/2015', null, false, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('7 Brentwood Crossing', 'stalled', null, '1/9/2015', null, false, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('19 Waywood Junction', 'preliminary', 3, '11/27/2014', 'stalled', true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('541 Ronald Regan Road', 'preliminary', 1, '11/1/2014', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('996 Arizona Junction', 'updated', 2, '10/9/2014', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('10 Tony Court', 'depreciated', 1, '6/26/2015', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('5957 Thackeray Crossing', 'stable', 3, '5/25/2015', 'cancelled', false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('1330 Sugar Alley', 'updated', 1, '5/30/2015', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('19 Northport Street', 'preliminary', 3, '4/1/2015', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('0594 Elka Drive', 'preliminary', 1, '5/13/2015', 'stalled', true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('9349 Miller Place', 'preliminary', 3, '5/1/2015', null, true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('09 Sunfield Terrace', 'preliminary', 3, '3/16/2015', 'stalled', true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('542 Kim Avenue', 'stable', 2, '12/30/2014', 'cancelled', false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('77 Schlimgen Point', 'stable', 1, '11/23/2014', 'cancelled', false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('23187 Lien Terrace', 'updated', 3, '7/27/2015', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('71 Sachs Hill', 'stable', 3, '4/11/2015', 'cancelled', true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('04973 Mifflin Avenue', 'preliminary', 2, '5/20/2015', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('40 Veith Court', 'updated', 2, '10/28/2014', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('78344 Burrows Alley', 'updated', 1, '4/24/2015', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('63 Northport Point', 'stalled', 2, '7/28/2015', 'pre', false, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('7484 Nevada Street', 'depreciated', null, '11/22/2014', 'inprogress', true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('93 Hermina Way', 'depreciated', 2, '10/9/2014', null, false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('04173 Muir Trail', 'depreciated', 3, '3/31/2015', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values (null, null, 2, null, null, null, null);
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('4 Del Sol Lane', 'depreciated', 1, '9/6/2014', null, false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('628 Killdeer Street', 'preliminary', 2, '10/20/2014', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('4970 Namekagon Way', 'depreciated', null, '6/28/2015', null, true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('5 Vidon Crossing', 'stalled', 3, '10/16/2014', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('26503 Coleman Circle', 'stalled', 2, '2/3/2015', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('8267 Springview Place', 'stable', 3, '12/31/2014', 'cancelled', true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('43516 Talmadge Circle', 'stable', 2, '6/3/2015', null, false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('4970 Namekagon Way', 'stalled', 2, '8/30/2014', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('0 Muir Trail', 'stalled', 1, '7/14/2015', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('719 Dawn Lane', 'stalled', 2, '3/28/2015', null, false, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('78305 Sachtjen Center', 'stable', null, '9/17/2014', 'cancelled', true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('38 Golf View Road', null, 2, '9/29/2014', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('54754 Talmadge Court', 'depreciated', 1, '7/23/2015', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('57947 Northridge Pass', 'depreciated', 2, '6/22/2015', 'inprogress', true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('1770 Kings Way', 'updated', 3, '1/16/2015', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('9433 South Hill', 'depreciated', null, '7/28/2015', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('49537 Ridgeview Park', null, 1, '5/22/2015', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('79168 Kipling Circle', 'depreciated', 3, '5/6/2015', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('9370 Petterle Parkway', 'stable', 3, '12/11/2014', 'cancelled', false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('09930 Westport Crossing', 'preliminary', null, '5/14/2015', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('55 Fisk Crossing', 'depreciated', 3, '4/16/2015', 'inprogress', true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('35295 Waubesa Way', 'updated', null, '4/24/2015', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('465 Vahlen Court', 'stalled', 1, '3/15/2015', 'pre', false, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('7362 Lyons Hill', 'depreciated', null, '4/26/2015', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('94 Blue Bill Park Alley', 'stalled', 3, '2/23/2015', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('051 Anniversary Parkway', 'preliminary', null, '12/20/2014', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('21481 Barby Plaza', 'stable', 1, '11/22/2014', 'cancelled', true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('8 Badeau Pass', 'stalled', 1, '10/30/2014', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('8 High Crossing Park', 'stalled', 1, '10/3/2014', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('17247 Kings Park', 'depreciated', 1, '5/2/2015', 'inprogress', true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('540 Manufacturers Center', 'preliminary', 1, '6/16/2015', 'stalled', true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('1 Menomonie Avenue', 'depreciated', 2, '12/30/2014', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('8 Mosinee Terrace', 'updated', 1, '5/8/2015', null, true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('2 Kedzie Trail', 'depreciated', 2, '2/22/2015', 'inprogress', true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('57947 Northridge Pass', 'updated', 1, '12/12/2014', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('26503 Coleman Circle', null, null, '6/2/2015', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('376 Tony Parkway', 'depreciated', 1, '1/11/2015', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('941 Carey Court', 'stalled', 3, '1/23/2015', null, true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('83441 Kingsford Court', 'depreciated', 3, '10/16/2014', null, true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('5 Stone Corner Place', 'depreciated', 3, '1/29/2015', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('1 Elgar Lane', 'stable', 1, '8/31/2014', null, false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('750 Pankratz Drive', 'stable', 1, '5/23/2015', 'cancelled', true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('20356 Sage Plaza', 'stalled', 3, '8/14/2014', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('45700 7th Way', 'stable', 3, '6/17/2015', 'cancelled', false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('719 Dawn Lane', 'preliminary', 2, '5/9/2015', null, true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('901 Lakeland Drive', 'updated', 3, '2/13/2015', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('83 Hoard Point', 'preliminary', 1, '7/18/2015', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values (null, 'preliminary', 3, null, 'stalled', null, null);
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('8 Melby Parkway', 'stable', 2, '8/26/2014', 'cancelled', false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('9 Pepper Wood Drive', 'updated', 3, '4/13/2015', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('3 Milwaukee Circle', 'stable', 3, '7/23/2015', 'cancelled', false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('94 Blue Bill Park Alley', null, 1, '8/28/2014', 'cancelled', false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('084 Southridge Avenue', 'updated', 3, '8/10/2015', null, true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('9 Burrows Street', 'depreciated', 1, '5/5/2015', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('865 Bay Park', 'depreciated', 1, '2/22/2015', null, true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('83 Hoard Point', 'updated', 1, '4/23/2015', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('4864 Norway Maple Street', 'preliminary', 2, '9/24/2014', 'stalled', true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('10 Tony Court', 'depreciated', 2, '2/22/2015', 'inprogress', true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('3358 Anthes Terrace', 'stable', 3, '3/25/2015', null, false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('57 Bunting Drive', 'depreciated', 1, '12/8/2014', 'inprogress', true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('0 Burning Wood Street', 'stalled', 1, '10/18/2014', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('7484 Nevada Street', 'preliminary', 2, '11/12/2014', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('83 Hoard Point', 'preliminary', 1, '1/8/2015', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('292 John Wall Junction', 'preliminary', 2, '6/19/2015', 'stalled', true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('0898 Dwight Court', 'stalled', 2, '5/30/2015', 'pre', false, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('1171 Del Mar Hill', 'preliminary', 3, '8/3/2015', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('93 Hermina Way', 'stalled', 2, '5/17/2015', 'pre', false, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('58 Lakeland Junction', 'preliminary', 2, '10/28/2014', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('3906 Prairieview Alley', 'stable', 3, '1/30/2015', 'cancelled', false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('95982 Green Alley', 'updated', 2, '8/22/2014', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('1171 Del Mar Hill', 'depreciated', 3, '9/29/2014', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('31 Trailsway Crossing', null, 2, '9/30/2014', 'stalled', true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('58 Lakeland Junction', 'stable', 3, '4/1/2015', 'cancelled', true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('5736 Talmadge Road', null, 3, '6/8/2015', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('9266 Browning Way', 'updated', 2, '6/23/2015', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('649 Cambridge Alley', 'stable', 2, '3/12/2015', 'cancelled', true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('28 Kim Road', 'preliminary', 3, '3/25/2015', null, true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('12288 Nobel Trail', 'stable', 3, '10/12/2014', 'cancelled', true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('0 Upham Plaza', null, 3, '10/3/2014', 'inprogress', true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('19 Waywood Junction', 'depreciated', 1, '4/17/2015', 'inprogress', true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('9 Dixon Avenue', 'depreciated', 2, '8/18/2014', 'inprogress', true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('79 Stuart Junction', 'depreciated', 2, '11/4/2014', null, true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('4541 Schiller Center', 'stable', 2, '2/4/2015', 'cancelled', false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('17247 Kings Park', 'updated', 3, '3/16/2015', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('3617 Rigney Hill', 'preliminary', 2, '6/5/2015', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('09930 Westport Crossing', 'stalled', 2, '9/11/2014', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('4852 Oneill Way', 'depreciated', 2, '10/28/2014', null, false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('75988 Becker Parkway', 'stalled', 2, '3/29/2015', 'pre', false, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('57 Bunting Drive', 'updated', 3, '12/16/2014', null, true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('15296 Onsgard Junction', 'preliminary', 3, '11/1/2014', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('5 Meadow Ridge Pass', 'depreciated', 2, '12/4/2014', 'inprogress', true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('5 Stone Corner Place', 'preliminary', 1, '10/11/2014', 'stalled', true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('0 Towne Terrace', 'preliminary', 2, '5/1/2015', null, true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('5 Vidon Crossing', 'preliminary', 2, '10/21/2014', null, true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('12288 Nobel Trail', 'stalled', 1, '4/5/2015', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('4852 Oneill Way', 'stalled', 2, '5/28/2015', null, false, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('55 Lukken Way', null, 3, '9/29/2014', 'pre', false, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('3 Brentwood Parkway', 'preliminary', 1, '4/5/2015', 'stalled', true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('2 Bowman Drive', 'updated', null, '2/23/2015', null, true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('45700 7th Way', 'preliminary', 2, '6/22/2015', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('383 Eastlawn Street', 'updated', 1, '3/30/2015', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('85 Derek Street', 'preliminary', 1, '8/4/2015', 'stalled', true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('8 Mosinee Terrace', 'preliminary', 3, '3/28/2015', 'stalled', true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('57 Bunting Drive', 'updated', 2, '3/28/2015', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('4970 Vera Terrace', 'depreciated', null, '4/27/2015', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('5957 Thackeray Crossing', 'stable', 2, '11/19/2014', 'cancelled', true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('5779 Elgar Circle', 'preliminary', 2, '4/26/2015', null, false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('456 Parkside Circle', 'stalled', 1, '5/12/2015', 'pre', false, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('937 Continental Lane', 'updated', 2, '10/4/2014', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('5779 Elgar Circle', 'updated', 2, '8/20/2014', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('5957 Thackeray Crossing', 'stalled', 2, '9/19/2014', 'pre', false, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('3 Marcy Pass', 'stalled', 2, '4/27/2015', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('718 Morrow Trail', 'stalled', 3, '8/25/2014', null, true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values (null, 'stable', 1, null, 'cancelled', null, null);
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('82610 Hauk Lane', 'depreciated', 3, '2/15/2015', null, true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('1861 Service Court', 'stable', 3, '7/28/2015', 'cancelled', true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('75988 Becker Parkway', 'updated', 3, '12/22/2014', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('12 Ridgeway Hill', 'stalled', 2, '12/27/2014', 'pre', false, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('63 Northport Point', 'updated', 2, '4/30/2015', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('322 Fairfield Pass', 'stalled', 1, '9/28/2014', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('1 Dapin Street', 'stable', 1, '8/18/2014', 'cancelled', true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('0290 Erie Drive', 'depreciated', null, '12/7/2014', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('865 Bay Park', 'stable', 2, '12/10/2014', 'cancelled', false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('57 Katie Terrace', 'stable', 3, '7/5/2015', 'cancelled', true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('7850 Orin Terrace', 'preliminary', 2, '11/1/2014', 'stalled', true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('4 Arkansas Alley', 'preliminary', 3, '8/20/2014', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('94 Redwing Road', 'preliminary', 3, '10/15/2014', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('465 Vahlen Court', 'stalled', 3, '10/4/2014', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('117 Monterey Crossing', 'stable', null, '8/2/2015', 'cancelled', true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('1109 Del Sol Alley', 'stalled', 2, '7/19/2015', null, true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('722 Caliangt Pass', 'updated', 1, '5/28/2015', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('996 Arizona Junction', 'stable', 2, '1/31/2015', 'cancelled', true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('08 Ohio Circle', 'updated', 2, '10/17/2014', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('4541 Schiller Center', 'updated', 3, '3/21/2015', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('86 Waxwing Alley', 'stable', 2, '7/4/2015', 'cancelled', true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values (null, null, 3, null, 'cancelled', null, null);
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('21481 Barby Plaza', 'depreciated', 3, '3/17/2015', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('383 Eastlawn Street', 'updated', 2, '4/14/2015', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('60 Loomis Plaza', 'depreciated', 1, '1/25/2015', 'inprogress', true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('8795 Amoth Trail', 'stable', 1, '11/22/2014', null, true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('43 Rieder Road', 'depreciated', 2, '10/19/2014', 'inprogress', true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('77 Almo Crossing', 'stalled', 2, '4/13/2015', 'pre', false, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('119 Holy Cross Crossing', 'preliminary', 1, '3/25/2015', null, true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('63 Northport Point', 'stalled', 2, '4/27/2015', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('23187 Lien Terrace', 'updated', 3, '10/7/2014', null, false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('20356 Sage Plaza', 'stalled', null, '4/26/2015', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('498 Nobel Pass', 'updated', 1, '3/29/2015', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('93 Hermina Way', 'depreciated', 1, '10/16/2014', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('70 Porter Point', null, 3, '11/12/2014', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('084 Southridge Avenue', 'updated', 3, '6/11/2015', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('04973 Mifflin Avenue', 'updated', 1, '10/7/2014', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('12288 Nobel Trail', 'stalled', 2, '7/14/2015', 'pre', false, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('43 Rieder Road', 'updated', 2, '8/20/2014', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('04173 Muir Trail', 'depreciated', 3, '5/5/2015', 'inprogress', true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('4 Eliot Junction', 'stalled', 2, '8/19/2014', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('5 Vidon Crossing', 'updated', 2, '4/26/2015', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('8 Badeau Pass', 'depreciated', null, '12/3/2014', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('3906 Prairieview Alley', 'depreciated', 3, '8/11/2015', 'inprogress', true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('77 Schlimgen Point', 'updated', 2, '7/17/2015', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values (null, 'stable', 3, null, 'cancelled', null, null);
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('57947 Northridge Pass', 'stable', 2, '7/24/2015', null, true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('83441 Kingsford Court', 'depreciated', 1, '6/15/2015', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('452 Rieder Junction', 'stable', 1, '1/6/2015', null, true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('098 Forest Place', 'stable', 2, '11/3/2014', 'cancelled', false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('452 Rieder Junction', 'depreciated', null, '5/28/2015', 'inprogress', true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('28743 Mccormick Park', 'preliminary', 3, '12/7/2014', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('452 Rieder Junction', 'preliminary', 3, '3/7/2015', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('19 Northport Street', 'depreciated', 3, '12/23/2014', 'inprogress', true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values (null, 'stalled', 2, null, null, null, null);
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('376 Tony Parkway', null, 1, '8/11/2015', 'stalled', true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('2154 Pine View Street', 'preliminary', 1, '8/14/2014', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('3617 Rigney Hill', 'updated', 3, '2/27/2015', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('85 Derek Street', 'stalled', 2, '7/23/2015', 'pre', false, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('453 Northland Plaza', 'depreciated', 3, '8/20/2014', 'inprogress', true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('28 Kim Road', 'updated', 1, '5/11/2015', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('71 Sachs Hill', 'stalled', null, '12/24/2014', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('08 Ohio Circle', null, 2, '7/21/2015', null, false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('23414 Stoughton Court', 'depreciated', 3, '10/6/2014', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('5957 Thackeray Crossing', null, 2, '10/30/2014', null, false, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('1 Menomonie Avenue', 'stalled', 2, '5/26/2015', 'pre', false, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('2987 Schmedeman Trail', 'updated', 2, '11/9/2014', null, true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('57 Bunting Drive', 'preliminary', null, '1/12/2015', null, false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('10 Bluejay Pass', 'stalled', 1, '11/30/2014', 'pre', false, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('4 Kensington Parkway', 'depreciated', 1, '7/3/2015', 'inprogress', true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('10791 Laurel Parkway', 'preliminary', 1, '4/4/2015', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('4541 Schiller Center', 'stalled', 1, '10/13/2014', null, true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('2519 Arapahoe Crossing', 'stable', 3, '1/12/2015', 'cancelled', false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('10 Bluejay Pass', 'depreciated', 3, '7/3/2015', 'inprogress', true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('4970 Vera Terrace', null, 1, '1/2/2015', 'inprogress', true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('26503 Coleman Circle', 'updated', 1, '6/16/2015', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('0 Towne Terrace', 'stable', 1, '5/2/2015', null, false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('48 Beilfuss Way', 'updated', 1, '12/10/2014', null, false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('542 Kim Avenue', 'preliminary', 1, '6/1/2015', 'stalled', true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('0 Upham Plaza', 'preliminary', 3, '11/9/2014', 'stalled', true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('452 Rieder Junction', 'stalled', 1, '7/12/2015', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('4712 Burning Wood Park', 'depreciated', 1, '8/21/2014', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('649 Cambridge Alley', 'updated', 2, '7/20/2015', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('12288 Nobel Trail', 'preliminary', 1, '5/23/2015', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('9266 Browning Way', 'updated', 1, '6/30/2015', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('3653 Springview Hill', 'updated', 3, '2/7/2015', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('1 Menomonie Avenue', 'updated', 1, '8/27/2014', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('04973 Mifflin Avenue', 'depreciated', 1, '4/3/2015', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('917 Green Ridge Center', 'updated', 1, '6/10/2015', null, true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('94 Moland Trail', 'stable', 3, '1/8/2015', 'cancelled', false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('97894 Stephen Court', 'preliminary', 3, '8/10/2015', null, true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('9 Burrows Street', 'depreciated', 1, '6/14/2015', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('628 Killdeer Street', 'depreciated', 1, '2/28/2015', null, false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('9 Dixon Avenue', 'stable', 2, '8/14/2014', 'cancelled', false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values (null, 'stalled', 1, null, 'pre', null, null);
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('91 Oneill Trail', 'updated', 2, '10/6/2014', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('051 Anniversary Parkway', 'stalled', 2, '1/28/2015', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('1 Jenna Lane', 'updated', 3, '4/27/2015', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('60 Loomis Plaza', 'stable', 3, '11/22/2014', 'cancelled', true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('712 Hoepker Parkway', 'preliminary', 2, '7/24/2015', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('06425 Glendale Plaza', 'stable', 1, '3/18/2015', null, true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('14 Katie Circle', 'updated', 3, '9/16/2014', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('295 Shelley Pass', 'stable', 3, '1/24/2015', null, false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('79168 Kipling Circle', 'stalled', 3, '7/15/2015', null, false, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('60638 Forest Crossing', 'updated', 2, '8/1/2015', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values (null, 'depreciated', 3, null, null, null, null);
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('7462 Magdeline Alley', 'stalled', 2, '2/14/2015', null, false, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('2 Arapahoe Plaza', 'stalled', 1, '5/24/2015', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('08 Melody Park', 'preliminary', 1, '7/13/2015', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('08 Ohio Circle', 'preliminary', 1, '4/29/2015', 'stalled', true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('86 Waxwing Alley', 'depreciated', 1, '8/7/2015', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('383 Eastlawn Street', 'stalled', 1, '8/11/2015', 'pre', false, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('45 Starling Circle', 'stalled', 2, '4/1/2015', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('1186 Mitchell Circle', 'stable', 1, '4/14/2015', 'cancelled', true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('718 Morrow Trail', 'stalled', 2, '9/20/2014', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('09079 Oxford Plaza', 'preliminary', 3, '3/25/2015', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('53 Artisan Circle', 'updated', 1, '7/24/2015', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('75651 Everett Park', 'stable', 3, '12/31/2014', 'cancelled', false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('8 Onsgard Junction', 'preliminary', 3, '8/25/2014', 'stalled', true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('60 Loomis Plaza', 'updated', 2, '3/26/2015', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('9433 South Hill', null, 3, '2/1/2015', null, false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('376 Tony Parkway', 'stable', 1, '4/27/2015', null, true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('37 Donald Street', 'depreciated', 3, '2/26/2015', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('712 Hoepker Parkway', 'stalled', 2, '5/27/2015', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('2 Walton Center', 'preliminary', 1, '6/12/2015', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('9809 Wayridge Park', 'preliminary', 3, '10/17/2014', 'stalled', true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('9809 Wayridge Park', 'updated', 2, '6/16/2015', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('69 Jana Circle', null, 3, '5/2/2015', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('399 Karstens Plaza', 'updated', 1, '6/11/2015', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('28 Kim Road', 'preliminary', 3, '5/30/2015', null, true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('98501 Hooker Junction', 'depreciated', null, '5/29/2015', 'inprogress', true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values (null, 'preliminary', 1, null, 'stalled', null, null);
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values (null, 'stalled', 3, null, 'pre', null, null);
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('04 Hovde Circle', 'stable', 3, '6/5/2015', 'cancelled', false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('04173 Muir Trail', 'preliminary', 2, '11/12/2014', 'stalled', true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('98 Arkansas Place', 'stable', 2, '5/28/2015', 'cancelled', false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('679 Prairie Rose Plaza', 'preliminary', 3, '11/6/2014', null, false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('517 Cambridge Hill', 'updated', 1, '2/17/2015', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('77 Schlimgen Point', 'stable', 2, '7/3/2015', 'cancelled', false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('541 Ronald Regan Road', 'stable', 2, '6/10/2015', 'cancelled', true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('4981 Blaine Lane', 'stalled', 1, '12/18/2014', null, false, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('498 Nobel Pass', 'stable', 2, '3/14/2015', 'cancelled', true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('45 Starling Circle', 'preliminary', 3, '8/29/2014', 'stalled', true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('9 Debs Hill', 'preliminary', 1, '11/26/2014', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('21 Towne Avenue', 'depreciated', 3, '10/10/2014', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('92 Melvin Junction', 'stable', 2, '1/11/2015', 'cancelled', false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('17247 Kings Park', 'depreciated', 3, '11/28/2014', null, true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('1315 Manitowish Parkway', 'stalled', 2, '7/7/2015', 'pre', false, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('0987 Lunder Junction', 'updated', 2, '4/25/2015', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('5 Stone Corner Place', 'depreciated', 1, '1/14/2015', null, false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('2 Bowman Drive', 'updated', 2, '1/26/2015', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('2154 Pine View Street', 'preliminary', 3, '7/24/2015', null, true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('2987 Schmedeman Trail', 'stable', 1, '7/25/2015', null, true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('12288 Nobel Trail', 'updated', 1, '2/20/2015', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('93 Hermina Way', 'preliminary', 1, '10/25/2014', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values (null, 'stalled', null, null, 'pre', null, null);
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('267 Oxford Terrace', 'updated', 1, '8/21/2014', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values (null, 'preliminary', null, null, 'stalled', null, null);
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('64 Sutteridge Street', 'preliminary', 1, '1/1/2015', 'stalled', true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('322 Fairfield Pass', 'stalled', 3, '12/24/2014', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('117 Monterey Crossing', 'depreciated', 3, '1/12/2015', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('7462 Magdeline Alley', 'depreciated', 1, '12/14/2014', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values (null, 'updated', 1, null, 'post', null, null);
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('132 Roxbury Parkway', 'preliminary', 3, '2/18/2015', null, false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('4970 Namekagon Way', 'preliminary', 2, '8/26/2014', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('0290 Erie Drive', 'stalled', 3, '1/5/2015', 'pre', true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('7 Brentwood Alley', 'stalled', null, '10/14/2014', 'pre', false, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('8 Carpenter Junction', 'preliminary', 3, '3/15/2015', 'stalled', false, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('475 Valley Edge Hill', 'updated', 1, '4/3/2015', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('70 Porter Point', 'depreciated', 3, '7/18/2015', 'inprogress', false, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('8795 Amoth Trail', 'updated', 1, '6/14/2015', null, true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('5779 Elgar Circle', 'updated', 2, '2/18/2015', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('1 Vidon Street', 'stalled', 1, '1/11/2015', 'pre', false, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values (null, 'stable', 1, null, 'cancelled', null, null);
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('86124 Golf Course Crossing', 'stable', 2, '12/4/2014', 'cancelled', false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('5 Melrose Terrace', 'preliminary', 3, '9/21/2014', 'stalled', true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('97894 Stephen Court', 'stable', 1, '9/30/2014', 'cancelled', false, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('453 Northland Plaza', 'depreciated', null, '7/12/2015', 'inprogress', true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('99441 Lunder Park', 'updated', 2, '10/5/2014', 'post', true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('7566 Laurel Place', 'preliminary', 1, '10/28/2014', 'stalled', true, 'XL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('53 Ohio Hill', 'depreciated', 3, '6/10/2015', 'inprogress', true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('34348 Northwestern Hill', 'stalled', 3, '11/2/2014', null, true, 'S');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('1315 Manitowish Parkway', 'updated', 2, '4/19/2015', 'post', false, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('28743 Mccormick Park', 'updated', 2, '9/25/2014', null, true, 'L');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('4852 Oneill Way', 'depreciated', 3, '8/30/2014', 'inprogress', true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('99778 Rigney Point', 'depreciated', 1, '10/12/2014', null, true, 'M');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('5779 Elgar Circle', 'stable', 2, '8/21/2014', 'cancelled', true, 'XXL');
insert into mock.data3 (address, status, grp, app_date, status2, done, type_a) values ('4 Spenser Park', 'updated', 2, '11/30/2014', 'post', true, 'L');
