create table mock.data2 (
	address VARCHAR(255),
	status VARCHAR(255),
	grp INT,
	type2 VARCHAR(255),
	app_date DATE,
	status2 VARCHAR(255),
	done VARCHAR(255)
);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('058 Kings Way', 'preliminary', 3, null, '5/16/2015', 'stalled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('0 Crowley Avenue', 'stable', 3, 'end', '1/24/2015', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('53 Ohio Hill', 'preliminary', 2, 'start', '9/23/2014', 'stalled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('12288 Nobel Trail', 'stalled', 3, 'end', '3/2/2015', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('54754 Talmadge Court', 'stable', 2, 'start', '3/14/2015', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('9 Ohio Plaza', 'stable', 1, null, '6/28/2015', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('97894 Stephen Court', 'updated', 1, 'start', '1/18/2015', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('540 Manufacturers Center', 'stable', 2, 'mid', '2/13/2015', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('621 Shopko Place', 'stable', 2, 'end', '4/19/2015', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('6 Algoma Trail', 'stalled', 2, 'mid', '10/23/2014', 'pre', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('09079 Oxford Plaza', 'preliminary', 3, null, '11/29/2014', 'stalled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('7462 Magdeline Alley', 'updated', 2, 'mid', '6/5/2015', 'post', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('3301 Birchwood Court', 'depreciated', 3, 'end', '4/7/2015', 'inprogress', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('4970 Namekagon Way', 'updated', 1, 'start', '10/8/2014', 'post', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('4 Arkansas Alley', 'preliminary', 2, 'end', '4/21/2015', 'stalled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('965 Farragut Road', 'depreciated', null, 'mid', '12/1/2014', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('21481 Barby Plaza', 'depreciated', 2, 'end', '1/19/2015', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('4852 Oneill Way', 'depreciated', 2, 'mid', '9/27/2014', 'inprogress', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('19 Waywood Junction', 'stable', 2, 'mid', '10/11/2014', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('7850 Orin Terrace', 'stalled', 3, 'mid', '5/14/2015', 'pre', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('1 Elgar Lane', 'stalled', 3, null, '8/23/2014', 'pre', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('7 Brentwood Crossing', 'stable', 3, 'mid', '2/28/2015', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('8795 Amoth Trail', 'stalled', 1, null, '10/16/2014', 'pre', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('354 Thompson Terrace', 'updated', 3, 'start', '12/19/2014', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('57 Katie Terrace', 'updated', 3, 'start', '6/8/2015', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('050 Loomis Park', 'stalled', 3, 'end', '1/11/2015', 'pre', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('8 Badeau Pass', 'depreciated', 3, 'mid', '6/8/2015', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('02 Village Pass', 'preliminary', 3, null, '12/14/2014', 'stalled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('0 Fisk Road', 'updated', 2, null, '10/27/2014', 'post', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('9 Debs Hill', 'stable', 3, 'mid', '11/16/2014', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('452 Rieder Junction', 'depreciated', 2, 'mid', '4/2/2015', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('70 Porter Point', 'stable', null, 'mid', '9/5/2014', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('9349 Miller Place', 'stable', 1, 'mid', '3/4/2015', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('7329 Sunbrook Hill', 'preliminary', 3, null, '8/26/2014', 'stalled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('965 Farragut Road', 'updated', 3, 'mid', '5/7/2015', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('611 Elka Plaza', 'preliminary', 2, 'end', '1/11/2015', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('2 Bowman Drive', 'stalled', 2, 'start', '10/17/2014', 'pre', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('542 Kim Avenue', 'depreciated', 1, 'start', '3/25/2015', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('77 Ludington Court', 'stable', 2, 'mid', '3/26/2015', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('02 Village Pass', 'updated', 2, 'mid', '4/11/2015', 'post', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('5 Veith Avenue', 'updated', 2, 'start', '10/13/2014', 'post', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('9 Burrows Street', 'updated', 1, 'mid', '1/6/2015', 'post', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('10 Tony Court', 'updated', 3, 'mid', '6/5/2015', 'post', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('750 Pankratz Drive', 'depreciated', 1, 'mid', '12/18/2014', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('57052 Myrtle Way', 'stalled', 2, 'end', '8/4/2015', 'pre', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('43 Rieder Road', 'updated', 3, 'end', '2/6/2015', 'post', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('542 Kim Avenue', 'preliminary', 1, 'mid', '12/19/2014', 'stalled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('5 Meadow Ridge Pass', 'stalled', 2, 'start', '9/4/2014', 'pre', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('771 Scoville Way', 'updated', 1, 'end', '1/19/2015', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('8875 Dorton Hill', 'stable', 3, 'mid', '7/15/2015', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('12 Ridgeway Hill', 'stable', 2, 'mid', '1/6/2015', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('322 Fairfield Pass', null, 3, 'mid', '8/26/2014', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('38 Golf View Road', 'updated', 3, 'mid', '5/23/2015', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('4970 Vera Terrace', 'depreciated', 2, null, '5/31/2015', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('09079 Oxford Plaza', 'preliminary', 1, 'end', '3/22/2015', 'stalled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('292 John Wall Junction', 'updated', 1, 'end', '2/2/2015', 'post', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('58 Lakeland Junction', 'stable', 1, 'end', '9/24/2014', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values (null, 'updated', null, 'start', null, 'post', null);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('718 Morrow Trail', 'preliminary', 1, 'start', '6/3/2015', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('09079 Oxford Plaza', 'depreciated', 3, 'end', '3/6/2015', 'inprogress', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('132 Roxbury Parkway', 'depreciated', 2, 'mid', '8/6/2015', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('38 Golf View Road', 'preliminary', 3, 'start', '8/25/2014', 'stalled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values (null, 'updated', 3, 'end', null, 'post', null);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('92 Melvin Junction', 'depreciated', 3, 'start', '2/4/2015', 'inprogress', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('31 Trailsway Crossing', 'preliminary', 3, 'end', '11/20/2014', 'stalled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values (null, 'preliminary', 3, 'end', null, 'stalled', null);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('38 Golf View Road', 'stalled', 1, 'end', '7/24/2015', 'pre', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('54 Maple Terrace', 'updated', 2, 'start', '8/21/2014', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('85 Derek Street', 'updated', 2, 'start', '12/3/2014', 'post', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('75 7th Place', 'stable', 2, 'start', '12/4/2014', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('91 Oneill Trail', 'preliminary', 1, 'start', '2/5/2015', 'stalled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('8 Cambridge Terrace', 'stable', 2, 'mid', '4/16/2015', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('72431 Farwell Crossing', 'depreciated', 1, 'start', '8/14/2014', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('45 Starling Circle', 'updated', 1, 'end', '8/13/2014', 'post', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('81859 Grayhawk Place', 'depreciated', 3, null, '10/5/2014', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('542 Kim Avenue', 'updated', 3, 'mid', '8/7/2015', 'post', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('7850 Orin Terrace', 'updated', 1, 'start', '7/4/2015', 'post', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('901 Lakeland Drive', null, 2, 'end', '9/27/2014', 'post', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('2154 Pine View Street', 'preliminary', 3, 'start', '8/8/2015', 'stalled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('5957 Thackeray Crossing', 'stalled', 2, null, '12/18/2014', 'pre', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('91 Oneill Trail', 'depreciated', 2, 'start', '7/5/2015', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('5834 Forster Pass', 'stalled', 2, 'start', '1/10/2015', 'pre', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('46 Independence Terrace', null, 1, 'mid', '11/23/2014', 'stalled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('715 Bowman Court', 'depreciated', 1, 'start', '2/22/2015', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('15296 Onsgard Junction', 'stable', 2, 'start', '12/12/2014', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('7 Oriole Junction', 'preliminary', 2, null, '8/18/2014', 'stalled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values (null, 'stable', 3, 'mid', null, null, null);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('46 Independence Terrace', 'stable', 2, 'mid', '6/18/2015', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('86 Waxwing Alley', 'stalled', 2, null, '9/12/2014', 'pre', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('1 Forest Street', 'preliminary', 3, 'mid', '8/22/2014', 'stalled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('12348 Birchwood Park', 'preliminary', null, null, '3/10/2015', 'stalled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('8995 Drewry Terrace', 'stable', 1, 'start', '11/25/2014', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('936 Moulton Park', 'stalled', 1, 'mid', '6/8/2015', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('3566 Artisan Trail', 'depreciated', 3, 'end', '3/17/2015', 'inprogress', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('734 Sullivan Junction', 'depreciated', 2, null, '6/18/2015', 'inprogress', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('8656 Valley Edge Avenue', 'depreciated', 2, 'mid', '12/20/2014', 'inprogress', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('2987 Schmedeman Trail', 'stalled', 2, 'mid', '9/28/2014', 'pre', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('267 Oxford Terrace', 'depreciated', 2, 'start', '2/10/2015', 'inprogress', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('12288 Nobel Trail', 'preliminary', 2, 'mid', '6/21/2015', 'stalled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('68951 Debra Plaza', 'depreciated', 3, 'mid', '5/3/2015', 'inprogress', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('37 Donald Street', 'stalled', 1, 'end', '10/10/2014', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('20356 Sage Plaza', 'updated', 2, 'start', '4/26/2015', 'post', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('36 Bartillon Center', 'updated', 1, null, '9/27/2014', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('75 Lotheville Court', 'stable', 1, 'end', '12/30/2014', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('1 Dapin Street', 'updated', 1, 'mid', '5/7/2015', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('9809 Wayridge Park', 'stable', 1, 'start', '8/21/2014', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('973 Heffernan Alley', null, 1, 'start', '8/20/2014', 'pre', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('1109 Del Sol Alley', 'preliminary', 1, 'mid', '1/7/2015', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('12 Ridgeway Hill', 'preliminary', 3, 'end', '9/13/2014', 'stalled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('5 Annamark Center', 'stable', 3, 'start', '4/17/2015', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('4970 Namekagon Way', 'depreciated', 2, 'end', '6/2/2015', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('10 Bluejay Pass', 'stable', 1, 'end', '7/19/2015', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('456 Parkside Circle', 'depreciated', 3, 'mid', '12/25/2014', 'inprogress', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('267 Oxford Terrace', 'stable', 2, 'start', '3/29/2015', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values (null, 'depreciated', 2, 'start', null, 'inprogress', null);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('0290 Erie Drive', 'depreciated', 3, 'mid', '9/1/2014', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('946 Kingsford Drive', 'updated', 3, 'mid', '9/6/2014', 'post', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('771 Scoville Way', 'stable', 1, 'mid', '12/15/2014', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('058 Kings Way', 'preliminary', 3, 'end', '7/9/2015', 'stalled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('10 Bluejay Pass', 'stable', 3, 'mid', '1/24/2015', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('1 Vidon Street', 'preliminary', 1, 'end', '7/20/2015', 'stalled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('0 Hansons Avenue', 'updated', 3, 'start', '1/2/2015', 'post', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('86 Waxwing Alley', 'updated', 3, 'end', '5/4/2015', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values (null, 'preliminary', 1, 'mid', null, 'stalled', null);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('1939 Grim Point', 'stable', 1, 'end', '6/22/2015', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('182 Dexter Alley', 'stable', 2, 'start', '8/26/2014', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('68097 Birchwood Center', 'stable', 1, null, '2/20/2015', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('9 Ohio Plaza', 'stable', 1, 'start', '8/9/2015', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('10 Tony Court', 'stalled', 2, 'mid', '7/13/2015', 'pre', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('9 Burrows Street', 'updated', 1, 'mid', '12/14/2014', 'post', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('5 Meadow Ridge Pass', 'stalled', 3, 'mid', '8/22/2014', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('098 Forest Place', null, 1, 'mid', '1/17/2015', 'pre', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('611 Elka Plaza', 'stable', 3, 'mid', '8/2/2015', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('4970 Namekagon Way', 'preliminary', null, 'end', '2/21/2015', 'stalled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('941 Carey Court', 'stalled', 3, 'end', '8/9/2015', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('64 Sutteridge Street', 'preliminary', 3, 'start', '1/24/2015', 'stalled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('8 Onsgard Junction', 'stalled', 3, 'start', '4/14/2015', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('81859 Grayhawk Place', 'preliminary', 2, 'end', '4/2/2015', 'stalled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('23414 Stoughton Court', 'updated', 1, 'start', '5/16/2015', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('8267 Springview Place', 'stable', 3, 'mid', '10/10/2014', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('58819 Hayes Circle', 'preliminary', 2, null, '4/21/2015', 'stalled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('4970 Namekagon Way', 'stable', 1, null, '11/17/2014', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('9 Dixon Avenue', 'updated', 2, 'end', '8/24/2014', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('259 Buell Place', 'stalled', 2, 'end', '1/8/2015', 'pre', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('98501 Hooker Junction', 'stable', 1, 'end', '2/9/2015', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('1 Menomonie Avenue', 'stalled', 3, 'end', '3/19/2015', 'pre', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('9433 South Hill', 'preliminary', 1, null, '12/1/2014', 'stalled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('1203 Crownhardt Drive', 'stalled', 3, null, '9/19/2014', 'pre', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('9 Burrows Street', 'stable', 2, 'start', '3/12/2015', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('04 Hovde Circle', 'updated', 3, 'mid', '9/17/2014', 'post', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('542 Kim Avenue', 'preliminary', 3, 'end', '1/15/2015', 'stalled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('46 Schurz Place', 'stalled', 3, 'start', '7/3/2015', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values (null, 'depreciated', 1, null, null, null, null);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('8 Mosinee Terrace', 'stable', 3, 'end', '9/2/2014', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('97894 Stephen Court', 'depreciated', 1, 'mid', '12/14/2014', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('058 Kings Way', 'stalled', 2, 'end', '12/15/2014', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('70825 Grim Place', 'preliminary', 2, 'end', '8/20/2014', 'stalled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('04 Pleasure Drive', 'updated', 2, 'start', '4/30/2015', 'post', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('0 Fisk Road', 'depreciated', 3, 'start', '8/24/2014', 'inprogress', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('95539 Menomonie Point', 'preliminary', 2, 'end', '7/5/2015', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values (null, 'stalled', 2, null, null, 'pre', null);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('456 Parkside Circle', 'stable', 3, null, '10/17/2014', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('456 Parkside Circle', 'stalled', 2, 'mid', '10/14/2014', 'pre', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('17247 Kings Park', null, 1, 'start', '12/31/2014', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('63 Northport Point', 'stalled', 2, 'mid', '6/27/2015', 'pre', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('5 Dayton Crossing', 'depreciated', 3, 'end', '7/30/2015', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('64 Sutteridge Street', 'depreciated', 3, 'end', '9/27/2014', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('5800 Bayside Crossing', 'preliminary', null, 'end', '6/2/2015', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('12 Barby Pass', 'stable', 1, 'mid', '4/17/2015', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('901 Lakeland Drive', 'updated', 3, 'mid', '4/4/2015', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('453 Northland Plaza', 'stalled', 3, null, '4/15/2015', 'pre', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('1 Menomonie Avenue', 'depreciated', 1, 'start', '1/1/2015', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('58819 Hayes Circle', 'depreciated', 1, 'end', '5/11/2015', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('94 Moland Trail', 'stable', 1, 'start', '3/20/2015', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('40 Veith Court', 'stable', 2, 'start', '11/21/2014', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('8888 Butterfield Lane', 'preliminary', 1, null, '12/4/2014', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('3 Milwaukee Circle', 'updated', 2, 'start', '10/16/2014', 'post', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('621 Shopko Place', 'depreciated', 2, 'end', '5/6/2015', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('99778 Rigney Point', 'updated', 1, 'start', '9/29/2014', 'post', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('55796 1st Pass', 'updated', 2, 'start', '1/4/2015', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('04 Pleasure Drive', 'updated', 2, 'start', '11/1/2014', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('06425 Glendale Plaza', 'stable', 1, null, '3/13/2015', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('38 Golf View Road', 'updated', 1, 'start', '7/22/2015', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('7362 Lyons Hill', null, 3, 'start', '9/30/2014', 'post', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('20356 Sage Plaza', 'preliminary', 3, 'mid', '8/13/2014', 'stalled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('25 Kenwood Way', 'preliminary', 2, 'end', '3/1/2015', 'stalled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('94 Moland Trail', 'updated', 1, null, '10/4/2014', 'post', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('57 Bunting Drive', 'updated', 2, 'mid', '1/9/2015', 'post', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('8888 Butterfield Lane', 'stalled', 2, 'mid', '2/14/2015', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('85 Derek Street', 'stalled', 3, 'start', '10/25/2014', 'pre', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('10791 Laurel Parkway', 'stable', 1, 'end', '8/24/2014', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('119 Holy Cross Crossing', 'preliminary', 2, 'mid', '8/3/2015', 'stalled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('9 Troy Park', 'stalled', 3, 'end', '9/20/2014', 'pre', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('1770 Kings Way', 'preliminary', null, 'start', '4/28/2015', 'stalled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('57 Bunting Drive', 'stalled', 1, 'start', '10/5/2014', 'pre', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('7566 Laurel Place', 'stalled', 2, 'mid', '1/23/2015', 'pre', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('1203 Crownhardt Drive', 'depreciated', 2, 'end', '9/20/2014', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('995 Union Terrace', 'updated', 2, 'start', '1/12/2015', 'post', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('3 Crest Line Way', 'stable', 3, 'end', '12/5/2014', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('9433 South Hill', 'depreciated', 1, 'end', '5/8/2015', 'inprogress', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('621 Shopko Place', 'preliminary', 1, 'mid', '2/27/2015', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('1676 Cody Court', 'depreciated', 2, 'mid', '7/12/2015', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('911 Rowland Street', 'preliminary', 1, 'end', '4/3/2015', 'stalled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('948 Valley Edge Street', 'depreciated', 2, 'start', '5/31/2015', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('94 Moland Trail', 'stable', 3, 'start', '1/12/2015', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('132 Roxbury Parkway', 'stalled', 3, 'mid', '12/6/2014', 'pre', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('5800 Bayside Crossing', 'stable', 3, null, '11/11/2014', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('4 Kensington Parkway', 'updated', 1, 'mid', '4/22/2015', 'post', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('948 Jana Avenue', 'updated', null, 'start', '9/12/2014', 'post', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('86 Waxwing Alley', 'stable', 3, 'mid', '8/7/2015', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('8656 Valley Edge Avenue', 'stable', 2, 'start', '11/24/2014', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('3 Crest Line Way', 'updated', 1, 'start', '12/4/2014', 'post', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('75651 Everett Park', 'stable', 1, 'mid', '1/19/2015', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('70 Porter Point', 'stable', 1, 'start', '3/29/2015', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values (null, 'depreciated', 2, 'end', null, null, null);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('1109 Del Sol Alley', 'stalled', 1, 'mid', '3/30/2015', 'pre', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('661 Petterle Drive', 'depreciated', 2, 'start', '3/29/2015', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('31 Trailsway Crossing', 'updated', 3, null, '6/4/2015', 'post', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('9 Pepper Wood Drive', 'updated', 2, 'mid', '8/11/2015', 'post', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('28743 Mccormick Park', 'stable', 2, 'end', '10/12/2014', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('93 Hermina Way', 'updated', 1, 'end', '9/29/2014', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('8 Melby Parkway', 'depreciated', 2, 'mid', '11/17/2014', 'inprogress', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('0987 Lunder Junction', 'depreciated', 2, null, '8/12/2015', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('25 Kenwood Way', 'stalled', 2, 'mid', '8/4/2015', 'pre', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('8 Badeau Pass', 'stable', 1, 'start', '7/13/2015', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('292 John Wall Junction', 'updated', 2, 'mid', '2/15/2015', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('77 Ludington Court', 'stalled', 3, 'start', '11/23/2014', 'pre', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('3 Brentwood Parkway', 'stable', 1, 'end', '12/9/2014', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('57947 Northridge Pass', 'updated', 3, null, '11/16/2014', 'post', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('10791 Laurel Parkway', 'preliminary', null, 'end', '11/25/2014', 'stalled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('5 Mayer Place', 'stable', 2, 'start', '10/21/2014', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('02 Village Pass', 'updated', 3, 'start', '12/18/2014', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('3301 Birchwood Court', 'depreciated', 3, null, '1/10/2015', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('7 Brentwood Alley', 'stable', 1, 'start', '4/28/2015', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('58819 Hayes Circle', 'stalled', 2, 'end', '1/7/2015', 'pre', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('94 Moland Trail', 'stable', 1, 'end', '11/23/2014', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values (null, 'updated', 3, 'mid', null, 'post', null);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('06425 Glendale Plaza', 'stable', 3, 'end', '2/23/2015', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('96 Dennis Plaza', 'stable', 2, 'mid', '8/5/2015', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('771 Scoville Way', 'stable', 1, 'end', '9/2/2014', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('75 7th Place', 'stalled', 3, 'end', '7/3/2015', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('0898 Dwight Court', 'stalled', 3, 'mid', '10/15/2014', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('23 1st Court', 'updated', 2, null, '9/24/2014', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('82610 Hauk Lane', 'stable', 2, 'mid', '8/16/2014', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('21 Towne Avenue', null, 3, 'end', '2/18/2015', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('722 Caliangt Pass', 'depreciated', 2, 'end', '9/1/2014', 'inprogress', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('661 Petterle Drive', 'depreciated', 1, 'mid', '8/12/2015', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('9 Pepper Wood Drive', 'depreciated', 1, 'start', '12/8/2014', 'inprogress', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('946 Kingsford Drive', 'depreciated', null, 'end', '9/8/2014', 'inprogress', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('08 Ohio Circle', 'stalled', 1, 'start', '9/21/2014', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('734 Sullivan Junction', 'stalled', 3, null, '1/19/2015', 'pre', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('104 Merchant Way', 'depreciated', 3, null, '7/28/2015', 'inprogress', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('996 Arizona Junction', 'depreciated', null, null, '7/19/2015', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('1330 Sugar Alley', 'stable', 2, 'mid', '4/25/2015', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('0 Fisk Road', 'depreciated', 1, 'end', '4/1/2015', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('57 Bunting Drive', 'stalled', 1, 'start', '2/17/2015', 'pre', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('30999 Mcguire Drive', 'stable', 3, 'end', '6/10/2015', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('5800 Bayside Crossing', 'preliminary', 2, 'mid', '8/22/2014', 'stalled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('0 Muir Trail', 'updated', 2, 'end', '1/26/2015', 'post', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('9809 Wayridge Park', 'preliminary', 2, null, '12/28/2014', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('3930 Fallview Parkway', 'stable', 1, 'mid', '1/15/2015', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('456 Parkside Circle', 'depreciated', null, null, '8/23/2014', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('4981 Blaine Lane', 'preliminary', 2, 'mid', '6/3/2015', 'stalled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('32771 Fuller Avenue', 'preliminary', 1, 'end', '1/31/2015', 'stalled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('2 Arapahoe Plaza', 'stable', 1, 'end', '2/8/2015', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('4 Kensington Parkway', 'updated', 3, 'start', '8/16/2014', 'post', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('0 Burning Wood Street', null, null, 'start', '10/1/2014', 'pre', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('94 Blue Bill Park Alley', 'stable', 1, 'start', '12/6/2014', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('40 Veith Court', 'depreciated', 3, 'start', '6/7/2015', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('0 Hansons Avenue', 'depreciated', 2, 'mid', '2/26/2015', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('0 Hansons Avenue', 'preliminary', 2, 'mid', '4/11/2015', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('1 Forest Street', 'preliminary', 3, 'end', '7/28/2015', 'stalled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('292 John Wall Junction', 'depreciated', 1, 'start', '7/7/2015', 'inprogress', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('68951 Debra Plaza', 'stable', 2, 'end', '11/9/2014', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('23414 Stoughton Court', 'depreciated', 3, 'mid', '5/20/2015', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('75 Lotheville Court', 'stalled', 3, null, '10/5/2014', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('7362 Lyons Hill', 'depreciated', 2, 'mid', '8/28/2014', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('54 Maple Terrace', 'preliminary', 3, 'mid', '8/5/2015', 'stalled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('292 John Wall Junction', 'depreciated', 3, 'end', '9/23/2014', 'inprogress', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('54 Maple Terrace', 'updated', 2, 'mid', '11/20/2014', 'post', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('2 Walton Center', 'depreciated', 1, null, '11/22/2014', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('182 Dexter Alley', 'updated', 1, null, '6/7/2015', 'post', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('7 Brentwood Crossing', 'stable', 1, 'mid', '8/7/2015', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('1 Jenna Lane', 'preliminary', 1, 'end', '9/20/2014', 'stalled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('12 Ridgeway Hill', 'stable', 3, 'start', '7/6/2015', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('611 Elka Plaza', 'stalled', 3, 'end', '4/21/2015', 'pre', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('498 Nobel Pass', 'preliminary', 2, 'end', '9/22/2014', 'stalled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('517 Cambridge Hill', 'updated', 3, 'start', '1/3/2015', 'post', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('1 Elgar Lane', 'depreciated', null, 'end', '1/6/2015', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('679 Prairie Rose Plaza', 'stable', 2, 'mid', '7/10/2015', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('0594 Elka Drive', 'updated', 1, 'end', '2/28/2015', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('1 Vidon Street', 'updated', 1, 'mid', '1/31/2015', 'post', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('08 Ohio Circle', 'updated', 3, 'mid', '4/16/2015', 'post', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('15296 Onsgard Junction', 'preliminary', 2, 'mid', '4/14/2015', 'stalled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('75988 Becker Parkway', 'preliminary', null, 'end', '10/18/2014', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('1171 Del Mar Hill', 'preliminary', 3, 'mid', '10/22/2014', 'stalled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('1109 Del Sol Alley', 'preliminary', 2, 'end', '11/24/2014', 'stalled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values (null, 'depreciated', 2, 'start', null, null, null);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('9349 Miller Place', 'stable', 1, 'mid', '7/7/2015', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('2154 Pine View Street', 'depreciated', 3, 'mid', '2/19/2015', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('4970 Namekagon Way', 'depreciated', 1, 'start', '5/15/2015', 'inprogress', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('051 Anniversary Parkway', null, 1, 'end', '3/11/2015', 'pre', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('10 Bluejay Pass', 'updated', 3, 'end', '3/20/2015', 'post', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('54 Maple Terrace', 'stable', 3, 'start', '5/5/2015', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('948 Valley Edge Street', 'stalled', 2, 'end', '12/1/2014', 'pre', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('734 Sullivan Junction', 'stable', 1, 'mid', '12/17/2014', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('08 Ohio Circle', 'depreciated', 1, 'start', '9/1/2014', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('35295 Waubesa Way', 'updated', 3, 'end', '7/2/2015', 'post', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('6 Algoma Trail', 'depreciated', 2, 'end', '8/15/2014', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('7362 Lyons Hill', 'stalled', 2, null, '9/25/2014', 'pre', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('08 Ohio Circle', 'updated', null, 'start', '1/17/2015', 'post', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('83 Hoard Point', 'updated', 1, null, '12/25/2014', 'post', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('0 Towne Terrace', 'stable', 2, 'mid', '4/12/2015', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('68097 Birchwood Center', 'stable', 2, 'start', '12/15/2014', 'cancelled', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('4864 Norway Maple Street', 'updated', 1, 'start', '1/10/2015', 'post', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values (null, 'stable', 2, 'start', null, 'cancelled', null);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('57 Katie Terrace', 'stalled', 1, 'mid', '2/1/2015', 'pre', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('35295 Waubesa Way', 'stalled', 2, 'mid', '3/2/2015', 'pre', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('57052 Myrtle Way', 'depreciated', 3, 'start', '8/13/2014', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('0 Hansons Avenue', 'updated', null, 'end', '9/18/2014', null, false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('965 Farragut Road', 'preliminary', 1, null, '6/30/2015', 'stalled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('104 Merchant Way', 'updated', 2, 'end', '11/27/2014', 'post', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('542 Kim Avenue', 'updated', 3, 'start', '10/26/2014', 'post', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('1 Forest Street', null, 1, 'start', '1/31/2015', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('611 Elka Plaza', 'stalled', 1, 'end', '12/23/2014', 'pre', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('750 Pankratz Drive', 'stalled', 1, null, '4/8/2015', 'pre', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('77 Schlimgen Point', null, 3, 'mid', '10/3/2014', 'pre', true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('21481 Barby Plaza', 'depreciated', 2, 'end', '6/4/2015', null, true);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('04 Hovde Circle', 'stable', 3, 'start', '12/4/2014', 'cancelled', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('98 Arkansas Place', 'updated', 3, 'start', '9/27/2014', 'post', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('78414 Farragut Point', 'updated', 3, 'mid', '3/6/2015', 'post', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('183 Pankratz Drive', 'depreciated', 1, 'start', '1/30/2015', 'inprogress', false);
insert into mock.data2 (address, status, grp, type2, app_date, status2, done) values ('3 Milwaukee Circle', 'updated', 2, 'end', '4/20/2015', 'post', false);

	ALTER TABLE "mock"."data2"
	ADD COLUMN "block" smallint;
	UPDATE "mock"."data2" SET "block"=NULLIF(floor(random()*(3)+1),3);
